[build]
builder = "nixpacks"
buildCommand = "npm run build:production"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
